name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  
  build:

    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-22.04]
        
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3

    
    - name: Create env file
      run: |
        touch .env
        echo SERVER_PORT = "8000" >> .env
        echo SERVER_HOST = "localhost" >> .env
        cat .env

    - name: Install dependencies
      run: make req

    - name: Run check
      run:
        pip install uvicorn
        make py-local
        
